### ISSUE TITLE
pip install fails on Python 3.12 because of `av` missing wheels

### ISSUE THREAD

**Issue by niksirbi** [talmolab/sleap-io#68]
Pip install fails for me in a Python3.12 environment. This is true both locally, and on GitHub actions runners, where I first [encountered the issue](https://github.com/neuroinformatics-unit/movement/pull/72#issuecomment-1783284546). 

I think this is because of the `av` (aka PyAV) dependency, which [doesn't provide wheels for Python 3.12 yet](https://github.com/PyAV-Org/PyAV/issues/1168).

I'm opening this just to let you folks know, it's not a blocker for us (yet). Just something to be aware of in case you want to explicitly support v3.12.

**Comment by yozachar** [comment]
```py
add av failed:
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 283, in 
install_candidate
    self.manager.install(can)
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/installers/manager.py", line 33, in install
    installer(str(prepared.build()), self.environment, prepared.direct_url())
                  ^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/models/candidates.py", line 395, in build
    self.wheel = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/wheel.py", line 26, in build
    requires = self._hook.get_requires_for_build_wheel(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 166, in 
get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/base.py", line 260, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/us-er/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/builders/base.py", line 107, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
  File "/tmp/pdm-build-env-wctn1yac-shared/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
    super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
  File "/tmp/pdm-build-env-wctn1yac-shared/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
    exec(code, locals())
  File "<string>", line 157, in <module>
  File "/tmp/pdm-build-env-wctn1yac-shared/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/tmp/pdm-build-env-wctn1yac-shared/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: av/logging.pyx
```

**Comment by niksirbi** [comment]
This issue seems to be resolved for now. PyAV has [managed to find several kind co-maintainers](https://github.com/PyAV-Org/PyAV/issues/1186), and [wheels for Python 3.12 have been released on PyPI](https://github.com/PyAV-Org/PyAV/issues/1168).

I'm able to `pip install sleap-io` in Python 3.12 environments.
Feel free to close the issue.
